<?php

    return [
        [
            "id" => 1,
            "title" => "Il Padrino",
            "original_title" => "The Godfather",
            "nationality" => "american",
            "date" => "1939-12-15",
            "vote" => 8.6,
        ],
        [
            "id" => 2,
            "title" => "Via Col Vento",
            "original_title" => "Gone With The Wind",
            "nationality" => "american",
            "date" => "1939-12-15",
            "vote" => 8.6,
        ],
        [
            "id" => 3,
            "title" => "Psycho",
            "original_title" => "Psycho",
            "nationality" => "american",
            "date" => "1960-06-16",
            "vote" => 9.4,
        ],
        [
            "id" => 4,
            "title" => "Gravity",
            "original_title" => "Gravity",
            "nationality" => "american/british",
            "date" => "2013-08-28",
            "vote" => 7.8,
        ],
        [
            "id" => 5,
            "title" => "Toy Story - Il Mondo Dei Giocattoli",
            "original_title" => "Toy Story",
            "nationality" => "american/british",
            "date" => "1995-11-19",
            "vote" => 9.0,
        ],
        [
            "id" => 6,
            "title" => "Pulp Fiction",
            "original_title" => "Pulp Fiction",
            "nationality" => "american",
            "date" => "1994-10-14",
            "vote" => 9.2,
        ],
        [
            "id" => 7,
            "title" => "Forrest Gump",
            "original_title" => "Forrest Gump",
            "nationality" => "american/british",
            "date" => "1994-06-23",
            "vote" => 8.8,
        ],
        [
            "id" => 8,
            "title" => "Guerre Stellari",
            "original_title" => "Star Wars",
            "nationality" => "american",
            "date" => "1977-05-25",
            "vote" => 8.6,
        ],
        [
            "id" => 9,
            "title" => "E.T. - L\'extra-terrestre",
            "original_title" => "E.T. The Extra-Terrestrial",
            "nationality" => "american",
            "date" => "1982-05-26",
            "vote" => 7.9,
        ],
        [
            "id" => 10,
            "title" => "Il silenzio degli innocenti",
            "original_title" => "The Silence of the Lambs",
            "nationality" => "american",
            "date" => "1991-01-30",
            "vote" => 8.6,
        ],
    ]
        
?>